// Mocks generated by Mockito 5.4.4 from annotations
// in sentry_flutter/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i12;

import 'package:flutter/services.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sentry/src/metrics/metric.dart' as _i14;
import 'package:sentry/src/metrics/metrics_api.dart' as _i5;
import 'package:sentry/src/profiling.dart' as _i9;
import 'package:sentry/src/sentry_tracer.dart' as _i3;
import 'package:sentry_flutter/sentry_flutter.dart' as _i2;
import 'package:sentry_flutter/src/native/native_app_start.dart' as _i11;
import 'package:sentry_flutter/src/native/native_frames.dart' as _i13;
import 'package:sentry_flutter/src/native/sentry_native_binding.dart' as _i10;

import 'mocks.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSentrySpanContext_0 extends _i1.SmartFake
    implements _i2.SentrySpanContext {
  _FakeSentrySpanContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeISentrySpan_2 extends _i1.SmartFake implements _i2.ISentrySpan {
  _FakeISentrySpan_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentryTraceHeader_3 extends _i1.SmartFake
    implements _i2.SentryTraceHeader {
  _FakeSentryTraceHeader_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentryTracer_4 extends _i1.SmartFake implements _i3.SentryTracer {
  _FakeSentryTracer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentryId_5 extends _i1.SmartFake implements _i2.SentryId {
  _FakeSentryId_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContexts_6 extends _i1.SmartFake implements _i2.Contexts {
  _FakeContexts_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentryTransaction_7 extends _i1.SmartFake
    implements _i2.SentryTransaction {
  _FakeSentryTransaction_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMethodCodec_8 extends _i1.SmartFake implements _i4.MethodCodec {
  _FakeMethodCodec_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBinaryMessenger_9 extends _i1.SmartFake
    implements _i4.BinaryMessenger {
  _FakeBinaryMessenger_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentryOptions_10 extends _i1.SmartFake implements _i2.SentryOptions {
  _FakeSentryOptions_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetricsApi_11 extends _i1.SmartFake implements _i5.MetricsApi {
  _FakeMetricsApi_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScope_12 extends _i1.SmartFake implements _i2.Scope {
  _FakeScope_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHub_13 extends _i1.SmartFake implements _i2.Hub {
  _FakeHub_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Callbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbacks extends _i1.Mock implements _i6.Callbacks {
  MockCallbacks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<Object?>? methodCallHandler(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(Invocation.method(
        #methodCallHandler,
        [
          method,
          arguments,
        ],
      )) as _i7.Future<Object?>?);
}

/// A class which mocks [Transport].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransport extends _i1.Mock implements _i2.Transport {
  MockTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.SentryId?> send(_i2.SentryEnvelope? envelope) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [envelope],
        ),
        returnValue: _i7.Future<_i2.SentryId?>.value(),
      ) as _i7.Future<_i2.SentryId?>);
}

/// A class which mocks [SentryTracer].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentryTracer extends _i1.Mock implements _i3.SentryTracer {
  MockSentryTracer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SentryTransactionNameSource get transactionNameSource =>
      (super.noSuchMethod(
        Invocation.getter(#transactionNameSource),
        returnValue: _i2.SentryTransactionNameSource.custom,
      ) as _i2.SentryTransactionNameSource);

  @override
  set transactionNameSource(
          _i2.SentryTransactionNameSource? _transactionNameSource) =>
      super.noSuchMethod(
        Invocation.setter(
          #transactionNameSource,
          _transactionNameSource,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set profiler(_i9.SentryProfiler? _profiler) => super.noSuchMethod(
        Invocation.setter(
          #profiler,
          _profiler,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set profileInfo(_i9.SentryProfileInfo? _profileInfo) => super.noSuchMethod(
        Invocation.setter(
          #profileInfo,
          _profileInfo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SentrySpanContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeSentrySpanContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.SentrySpanContext);

  @override
  set origin(String? origin) => super.noSuchMethod(
        Invocation.setter(
          #origin,
          origin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  DateTime get startTimestamp => (super.noSuchMethod(
        Invocation.getter(#startTimestamp),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#startTimestamp),
        ),
      ) as DateTime);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get finished => (super.noSuchMethod(
        Invocation.getter(#finished),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.SentrySpan> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i2.SentrySpan>[],
      ) as List<_i2.SentrySpan>);

  @override
  set throwable(dynamic throwable) => super.noSuchMethod(
        Invocation.setter(
          #throwable,
          throwable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set status(_i2.SpanStatus? status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          status,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, _i2.SentryMeasurement> get measurements => (super.noSuchMethod(
        Invocation.getter(#measurements),
        returnValue: <String, _i2.SentryMeasurement>{},
      ) as Map<String, _i2.SentryMeasurement>);

  @override
  _i7.Future<void> finish({
    _i2.SpanStatus? status,
    DateTime? endTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finish,
          [],
          {
            #status: status,
            #endTimestamp: endTimestamp,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void removeData(String? key) => super.noSuchMethod(
        Invocation.method(
          #removeData,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeTag(String? key) => super.noSuchMethod(
        Invocation.method(
          #removeTag,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setData(
    String? key,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setData,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTag(
    String? key,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTag,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ISentrySpan startChild(
    String? operation, {
    String? description,
    DateTime? startTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startChild,
          [operation],
          {
            #description: description,
            #startTimestamp: startTimestamp,
          },
        ),
        returnValue: _FakeISentrySpan_2(
          this,
          Invocation.method(
            #startChild,
            [operation],
            {
              #description: description,
              #startTimestamp: startTimestamp,
            },
          ),
        ),
      ) as _i2.ISentrySpan);

  @override
  _i2.ISentrySpan startChildWithParentSpanId(
    _i2.SpanId? parentSpanId,
    String? operation, {
    String? description,
    DateTime? startTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startChildWithParentSpanId,
          [
            parentSpanId,
            operation,
          ],
          {
            #description: description,
            #startTimestamp: startTimestamp,
          },
        ),
        returnValue: _FakeISentrySpan_2(
          this,
          Invocation.method(
            #startChildWithParentSpanId,
            [
              parentSpanId,
              operation,
            ],
            {
              #description: description,
              #startTimestamp: startTimestamp,
            },
          ),
        ),
      ) as _i2.ISentrySpan);

  @override
  _i2.SentryTraceHeader toSentryTrace() => (super.noSuchMethod(
        Invocation.method(
          #toSentryTrace,
          [],
        ),
        returnValue: _FakeSentryTraceHeader_3(
          this,
          Invocation.method(
            #toSentryTrace,
            [],
          ),
        ),
      ) as _i2.SentryTraceHeader);

  @override
  void setMeasurement(
    String? name,
    num? value, {
    _i2.SentryMeasurementUnit? unit,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setMeasurement,
          [
            name,
            value,
          ],
          {#unit: unit},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleFinish() => super.noSuchMethod(
        Invocation.method(
          #scheduleFinish,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SentryTransaction].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockSentryTransaction extends _i1.Mock implements _i2.SentryTransaction {
  MockSentryTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get startTimestamp => (super.noSuchMethod(
        Invocation.getter(#startTimestamp),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#startTimestamp),
        ),
      ) as DateTime);

  @override
  set startTimestamp(DateTime? _startTimestamp) => super.noSuchMethod(
        Invocation.setter(
          #startTimestamp,
          _startTimestamp,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.SentrySpan> get spans => (super.noSuchMethod(
        Invocation.getter(#spans),
        returnValue: <_i2.SentrySpan>[],
      ) as List<_i2.SentrySpan>);

  @override
  set spans(List<_i2.SentrySpan>? _spans) => super.noSuchMethod(
        Invocation.setter(
          #spans,
          _spans,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SentryTracer get tracer => (super.noSuchMethod(
        Invocation.getter(#tracer),
        returnValue: _FakeSentryTracer_4(
          this,
          Invocation.getter(#tracer),
        ),
      ) as _i3.SentryTracer);

  @override
  Map<String, _i2.SentryMeasurement> get measurements => (super.noSuchMethod(
        Invocation.getter(#measurements),
        returnValue: <String, _i2.SentryMeasurement>{},
      ) as Map<String, _i2.SentryMeasurement>);

  @override
  set measurements(Map<String, _i2.SentryMeasurement>? _measurements) =>
      super.noSuchMethod(
        Invocation.setter(
          #measurements,
          _measurements,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set metricSummaries(Map<String, List<_i2.MetricSummary>>? _metricSummaries) =>
      super.noSuchMethod(
        Invocation.setter(
          #metricSummaries,
          _metricSummaries,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set transactionInfo(_i2.SentryTransactionInfo? _transactionInfo) =>
      super.noSuchMethod(
        Invocation.setter(
          #transactionInfo,
          _transactionInfo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get finished => (super.noSuchMethod(
        Invocation.getter(#finished),
        returnValue: false,
      ) as bool);

  @override
  bool get sampled => (super.noSuchMethod(
        Invocation.getter(#sampled),
        returnValue: false,
      ) as bool);

  @override
  _i2.SentryId get eventId => (super.noSuchMethod(
        Invocation.getter(#eventId),
        returnValue: _FakeSentryId_5(
          this,
          Invocation.getter(#eventId),
        ),
      ) as _i2.SentryId);

  @override
  _i2.Contexts get contexts => (super.noSuchMethod(
        Invocation.getter(#contexts),
        returnValue: _FakeContexts_6(
          this,
          Invocation.getter(#contexts),
        ),
      ) as _i2.Contexts);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.SentryTransaction copyWith({
    _i2.SentryId? eventId,
    DateTime? timestamp,
    String? platform,
    String? logger,
    String? serverName,
    String? release,
    String? dist,
    String? environment,
    Map<String, String>? modules,
    _i2.SentryMessage? message,
    String? transaction,
    dynamic throwable,
    _i2.SentryLevel? level,
    String? culprit,
    Map<String, String>? tags,
    Map<String, dynamic>? extra,
    List<String>? fingerprint,
    _i2.SentryUser? user,
    _i2.Contexts? contexts,
    List<_i2.Breadcrumb>? breadcrumbs,
    _i2.SdkVersion? sdk,
    _i2.SentryRequest? request,
    _i2.DebugMeta? debugMeta,
    List<_i2.SentryException>? exceptions,
    List<_i2.SentryThread>? threads,
    String? type,
    Map<String, _i2.SentryMeasurement>? measurements,
    Map<String, List<_i2.MetricSummary>>? metricSummaries,
    _i2.SentryTransactionInfo? transactionInfo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #eventId: eventId,
            #timestamp: timestamp,
            #platform: platform,
            #logger: logger,
            #serverName: serverName,
            #release: release,
            #dist: dist,
            #environment: environment,
            #modules: modules,
            #message: message,
            #transaction: transaction,
            #throwable: throwable,
            #level: level,
            #culprit: culprit,
            #tags: tags,
            #extra: extra,
            #fingerprint: fingerprint,
            #user: user,
            #contexts: contexts,
            #breadcrumbs: breadcrumbs,
            #sdk: sdk,
            #request: request,
            #debugMeta: debugMeta,
            #exceptions: exceptions,
            #threads: threads,
            #type: type,
            #measurements: measurements,
            #metricSummaries: metricSummaries,
            #transactionInfo: transactionInfo,
          },
        ),
        returnValue: _FakeSentryTransaction_7(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #eventId: eventId,
              #timestamp: timestamp,
              #platform: platform,
              #logger: logger,
              #serverName: serverName,
              #release: release,
              #dist: dist,
              #environment: environment,
              #modules: modules,
              #message: message,
              #transaction: transaction,
              #throwable: throwable,
              #level: level,
              #culprit: culprit,
              #tags: tags,
              #extra: extra,
              #fingerprint: fingerprint,
              #user: user,
              #contexts: contexts,
              #breadcrumbs: breadcrumbs,
              #sdk: sdk,
              #request: request,
              #debugMeta: debugMeta,
              #exceptions: exceptions,
              #threads: threads,
              #type: type,
              #measurements: measurements,
              #metricSummaries: metricSummaries,
              #transactionInfo: transactionInfo,
            },
          ),
        ),
      ) as _i2.SentryTransaction);
}

/// A class which mocks [SentrySpan].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentrySpan extends _i1.Mock implements _i2.SentrySpan {
  MockSentrySpan() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRootSpan => (super.noSuchMethod(
        Invocation.getter(#isRootSpan),
        returnValue: false,
      ) as bool);

  @override
  _i3.SentryTracer get tracer => (super.noSuchMethod(
        Invocation.getter(#tracer),
        returnValue: _FakeSentryTracer_4(
          this,
          Invocation.getter(#tracer),
        ),
      ) as _i3.SentryTracer);

  @override
  set status(_i2.SpanStatus? status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          status,
        ),
        returnValueForMissingStub: null,
      );

  @override
  DateTime get startTimestamp => (super.noSuchMethod(
        Invocation.getter(#startTimestamp),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#startTimestamp),
        ),
      ) as DateTime);

  @override
  _i2.SentrySpanContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeSentrySpanContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.SentrySpanContext);

  @override
  set origin(String? origin) => super.noSuchMethod(
        Invocation.setter(
          #origin,
          origin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get finished => (super.noSuchMethod(
        Invocation.getter(#finished),
        returnValue: false,
      ) as bool);

  @override
  set throwable(dynamic throwable) => super.noSuchMethod(
        Invocation.setter(
          #throwable,
          throwable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<void> finish({
    _i2.SpanStatus? status,
    DateTime? endTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finish,
          [],
          {
            #status: status,
            #endTimestamp: endTimestamp,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void removeData(String? key) => super.noSuchMethod(
        Invocation.method(
          #removeData,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeTag(String? key) => super.noSuchMethod(
        Invocation.method(
          #removeTag,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setData(
    String? key,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setData,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTag(
    String? key,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTag,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ISentrySpan startChild(
    String? operation, {
    String? description,
    DateTime? startTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startChild,
          [operation],
          {
            #description: description,
            #startTimestamp: startTimestamp,
          },
        ),
        returnValue: _FakeISentrySpan_2(
          this,
          Invocation.method(
            #startChild,
            [operation],
            {
              #description: description,
              #startTimestamp: startTimestamp,
            },
          ),
        ),
      ) as _i2.ISentrySpan);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.SentryTraceHeader toSentryTrace() => (super.noSuchMethod(
        Invocation.method(
          #toSentryTrace,
          [],
        ),
        returnValue: _FakeSentryTraceHeader_3(
          this,
          Invocation.method(
            #toSentryTrace,
            [],
          ),
        ),
      ) as _i2.SentryTraceHeader);

  @override
  void setMeasurement(
    String? name,
    num? value, {
    _i2.SentryMeasurementUnit? unit,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setMeasurement,
          [
            name,
            value,
          ],
          {#unit: unit},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleFinish() => super.noSuchMethod(
        Invocation.method(
          #scheduleFinish,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i4.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i4.MethodCodec get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMethodCodec_8(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i4.MethodCodec);

  @override
  _i4.BinaryMessenger get binaryMessenger => (super.noSuchMethod(
        Invocation.getter(#binaryMessenger),
        returnValue: _FakeBinaryMessenger_9(
          this,
          Invocation.getter(#binaryMessenger),
        ),
      ) as _i4.BinaryMessenger);

  @override
  _i7.Future<T?> invokeMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<List<T>?> invokeListMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeListMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i7.Future<List<T>?>.value(),
      ) as _i7.Future<List<T>?>);

  @override
  _i7.Future<Map<K, V>?> invokeMapMethod<K, V>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invokeMapMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i7.Future<Map<K, V>?>.value(),
      ) as _i7.Future<Map<K, V>?>);

  @override
  void setMethodCallHandler(
          _i7.Future<dynamic> Function(_i4.MethodCall)? handler) =>
      super.noSuchMethod(
        Invocation.method(
          #setMethodCallHandler,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SentryNativeBinding].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentryNativeBinding extends _i1.Mock
    implements _i10.SentryNativeBinding {
  MockSentryNativeBinding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> init(_i2.Hub? hub) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [hub],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i11.NativeAppStart?> fetchNativeAppStart() => (super.noSuchMethod(
        Invocation.method(
          #fetchNativeAppStart,
          [],
        ),
        returnValue: _i7.Future<_i11.NativeAppStart?>.value(),
      ) as _i7.Future<_i11.NativeAppStart?>);

  @override
  _i7.Future<void> captureEnvelope(
    _i12.Uint8List? envelopeData,
    bool? containsUnhandledException,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureEnvelope,
          [
            envelopeData,
            containsUnhandledException,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> beginNativeFrames() => (super.noSuchMethod(
        Invocation.method(
          #beginNativeFrames,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i13.NativeFrames?> endNativeFrames(_i2.SentryId? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #endNativeFrames,
          [id],
        ),
        returnValue: _i7.Future<_i13.NativeFrames?>.value(),
      ) as _i7.Future<_i13.NativeFrames?>);

  @override
  _i7.Future<void> setUser(_i2.SentryUser? user) => (super.noSuchMethod(
        Invocation.method(
          #setUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addBreadcrumb(_i2.Breadcrumb? breadcrumb) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBreadcrumb,
          [breadcrumb],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearBreadcrumbs() => (super.noSuchMethod(
        Invocation.method(
          #clearBreadcrumbs,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> loadContexts() => (super.noSuchMethod(
        Invocation.method(
          #loadContexts,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> setContexts(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setContexts,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeContexts(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeContexts,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setExtra(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExtra,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeExtra(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeExtra,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setTag(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTag,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeTag(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeTag,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  int? startProfiler(_i2.SentryId? traceId) =>
      (super.noSuchMethod(Invocation.method(
        #startProfiler,
        [traceId],
      )) as int?);

  @override
  _i7.Future<void> discardProfiler(_i2.SentryId? traceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #discardProfiler,
          [traceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int?> displayRefreshRate() => (super.noSuchMethod(
        Invocation.method(
          #displayRefreshRate,
          [],
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);

  @override
  _i7.Future<Map<String, dynamic>?> collectProfile(
    _i2.SentryId? traceId,
    int? startTimeNs,
    int? endTimeNs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectProfile,
          [
            traceId,
            startTimeNs,
            endTimeNs,
          ],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<_i2.DebugImage>?> loadDebugImages() => (super.noSuchMethod(
        Invocation.method(
          #loadDebugImages,
          [],
        ),
        returnValue: _i7.Future<List<_i2.DebugImage>?>.value(),
      ) as _i7.Future<List<_i2.DebugImage>?>);

  @override
  _i7.Future<void> pauseAppHangTracking() => (super.noSuchMethod(
        Invocation.method(
          #pauseAppHangTracking,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resumeAppHangTracking() => (super.noSuchMethod(
        Invocation.method(
          #resumeAppHangTracking,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.SentryId> captureReplay(bool? isCrash) => (super.noSuchMethod(
        Invocation.method(
          #captureReplay,
          [isCrash],
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureReplay,
            [isCrash],
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);
}

/// A class which mocks [Hub].
///
/// See the documentation for Mockito's code generation for more information.
class MockHub extends _i1.Mock implements _i2.Hub {
  MockHub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SentryOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeSentryOptions_10(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.SentryOptions);

  @override
  _i5.MetricsApi get metricsApi => (super.noSuchMethod(
        Invocation.getter(#metricsApi),
        returnValue: _FakeMetricsApi_11(
          this,
          Invocation.getter(#metricsApi),
        ),
      ) as _i5.MetricsApi);

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i2.SentryId get lastEventId => (super.noSuchMethod(
        Invocation.getter(#lastEventId),
        returnValue: _FakeSentryId_5(
          this,
          Invocation.getter(#lastEventId),
        ),
      ) as _i2.SentryId);

  @override
  _i2.Scope get scope => (super.noSuchMethod(
        Invocation.getter(#scope),
        returnValue: _FakeScope_12(
          this,
          Invocation.getter(#scope),
        ),
      ) as _i2.Scope);

  @override
  set profilerFactory(_i9.SentryProfilerFactory? value) => super.noSuchMethod(
        Invocation.setter(
          #profilerFactory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.SentryId> captureEvent(
    _i2.SentryEvent? event, {
    dynamic stackTrace,
    _i2.Hint? hint,
    _i2.ScopeCallback? withScope,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureEvent,
          [event],
          {
            #stackTrace: stackTrace,
            #hint: hint,
            #withScope: withScope,
          },
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureEvent,
            [event],
            {
              #stackTrace: stackTrace,
              #hint: hint,
              #withScope: withScope,
            },
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);

  @override
  _i7.Future<_i2.SentryId> captureException(
    dynamic throwable, {
    dynamic stackTrace,
    _i2.Hint? hint,
    _i2.ScopeCallback? withScope,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureException,
          [throwable],
          {
            #stackTrace: stackTrace,
            #hint: hint,
            #withScope: withScope,
          },
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureException,
            [throwable],
            {
              #stackTrace: stackTrace,
              #hint: hint,
              #withScope: withScope,
            },
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);

  @override
  _i7.Future<_i2.SentryId> captureMessage(
    String? message, {
    _i2.SentryLevel? level,
    String? template,
    List<dynamic>? params,
    _i2.Hint? hint,
    _i2.ScopeCallback? withScope,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureMessage,
          [message],
          {
            #level: level,
            #template: template,
            #params: params,
            #hint: hint,
            #withScope: withScope,
          },
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureMessage,
            [message],
            {
              #level: level,
              #template: template,
              #params: params,
              #hint: hint,
              #withScope: withScope,
            },
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);

  @override
  _i7.Future<void> captureUserFeedback(_i2.SentryUserFeedback? userFeedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureUserFeedback,
          [userFeedback],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addBreadcrumb(
    _i2.Breadcrumb? crumb, {
    _i2.Hint? hint,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBreadcrumb,
          [crumb],
          {#hint: hint},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void bindClient(_i2.SentryClient? client) => super.noSuchMethod(
        Invocation.method(
          #bindClient,
          [client],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Hub clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeHub_13(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i2.Hub);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.FutureOr<void> configureScope(_i2.ScopeCallback? callback) =>
      (super.noSuchMethod(Invocation.method(
        #configureScope,
        [callback],
      )) as _i7.FutureOr<void>);

  @override
  _i2.ISentrySpan startTransaction(
    String? name,
    String? operation, {
    String? description,
    DateTime? startTimestamp,
    bool? bindToScope,
    bool? waitForChildren,
    Duration? autoFinishAfter,
    bool? trimEnd,
    _i2.OnTransactionFinish? onFinish,
    Map<String, dynamic>? customSamplingContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTransaction,
          [
            name,
            operation,
          ],
          {
            #description: description,
            #startTimestamp: startTimestamp,
            #bindToScope: bindToScope,
            #waitForChildren: waitForChildren,
            #autoFinishAfter: autoFinishAfter,
            #trimEnd: trimEnd,
            #onFinish: onFinish,
            #customSamplingContext: customSamplingContext,
          },
        ),
        returnValue: _i6.startTransactionShim(
          name,
          operation,
          description: description,
          startTimestamp: startTimestamp,
          bindToScope: bindToScope,
          waitForChildren: waitForChildren,
          autoFinishAfter: autoFinishAfter,
          trimEnd: trimEnd,
          onFinish: onFinish,
          customSamplingContext: customSamplingContext,
        ),
      ) as _i2.ISentrySpan);

  @override
  _i2.ISentrySpan startTransactionWithContext(
    _i2.SentryTransactionContext? transactionContext, {
    Map<String, dynamic>? customSamplingContext,
    DateTime? startTimestamp,
    bool? bindToScope,
    bool? waitForChildren,
    Duration? autoFinishAfter,
    bool? trimEnd,
    _i2.OnTransactionFinish? onFinish,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTransactionWithContext,
          [transactionContext],
          {
            #customSamplingContext: customSamplingContext,
            #startTimestamp: startTimestamp,
            #bindToScope: bindToScope,
            #waitForChildren: waitForChildren,
            #autoFinishAfter: autoFinishAfter,
            #trimEnd: trimEnd,
            #onFinish: onFinish,
          },
        ),
        returnValue: _FakeISentrySpan_2(
          this,
          Invocation.method(
            #startTransactionWithContext,
            [transactionContext],
            {
              #customSamplingContext: customSamplingContext,
              #startTimestamp: startTimestamp,
              #bindToScope: bindToScope,
              #waitForChildren: waitForChildren,
              #autoFinishAfter: autoFinishAfter,
              #trimEnd: trimEnd,
              #onFinish: onFinish,
            },
          ),
        ),
      ) as _i2.ISentrySpan);

  @override
  _i7.Future<_i2.SentryId> captureTransaction(
    _i2.SentryTransaction? transaction, {
    _i2.SentryTraceContextHeader? traceContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureTransaction,
          [transaction],
          {#traceContext: traceContext},
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureTransaction,
            [transaction],
            {#traceContext: traceContext},
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);

  @override
  _i7.Future<_i2.SentryId> captureMetrics(
          Map<int, Iterable<_i14.Metric>>? metricsBuckets) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureMetrics,
          [metricsBuckets],
        ),
        returnValue: _i7.Future<_i2.SentryId>.value(_FakeSentryId_5(
          this,
          Invocation.method(
            #captureMetrics,
            [metricsBuckets],
          ),
        )),
      ) as _i7.Future<_i2.SentryId>);

  @override
  void setSpanContext(
    dynamic throwable,
    _i2.ISentrySpan? span,
    String? transaction,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSpanContext,
          [
            throwable,
            span,
            transaction,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
