// Mocks generated by Mockito 5.1.0 from annotations
// in sentry_flutter/example/ios/.symlinks/plugins/sentry_flutter/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter/src/services/binary_messenger.dart' as _i4;
import 'package:flutter/src/services/message_codec.dart' as _i3;
import 'package:flutter/src/services/platform_channel.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sentry/sentry.dart' as _i2;
import 'package:sentry/src/client_reports/discard_reason.dart' as _i10;
import 'package:sentry/src/sentry_envelope_header.dart' as _i5;
import 'package:sentry/src/transport/data_category.dart' as _i11;
import 'package:sentry_flutter/src/sentry_native.dart' as _i8;
import 'package:sentry_flutter/src/sentry_native_channel.dart' as _i9;

import 'mocks.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClientReportRecorder_0 extends _i1.Fake
    implements _i2.ClientReportRecorder {}

class _FakeSentrySpanContext_1 extends _i1.Fake
    implements _i2.SentrySpanContext {}

class _FakeDateTime_2 extends _i1.Fake implements DateTime {}

class _FakeISentrySpan_3 extends _i1.Fake implements _i2.ISentrySpan {}

class _FakeSentryTraceHeader_4 extends _i1.Fake
    implements _i2.SentryTraceHeader {}

class _FakeMethodCodec_5 extends _i1.Fake implements _i3.MethodCodec {}

class _FakeBinaryMessenger_6 extends _i1.Fake implements _i4.BinaryMessenger {}

class _FakeSentryEnvelopeHeader_7 extends _i1.Fake
    implements _i5.SentryEnvelopeHeader {}

class _FakeSentryOptions_8 extends _i1.Fake implements _i2.SentryOptions {}

class _FakeSentryId_9 extends _i1.Fake implements _i2.SentryId {}

class _FakeHub_10 extends _i1.Fake implements _i2.Hub {}

/// A class which mocks [Transport].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransport extends _i1.Mock implements _i2.Transport {
  MockTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientReportRecorder get recorder => (super.noSuchMethod(
      Invocation.getter(#recorder),
      returnValue: _FakeClientReportRecorder_0()) as _i2.ClientReportRecorder);
  @override
  _i6.Future<_i2.SentryId?> send(_i2.SentryEnvelope? envelope) =>
      (super.noSuchMethod(Invocation.method(#send, [envelope]),
              returnValue: Future<_i2.SentryId?>.value())
          as _i6.Future<_i2.SentryId?>);
}

/// A class which mocks [NoOpSentrySpan].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoOpSentrySpan extends _i1.Mock implements _i2.NoOpSentrySpan {
  MockNoOpSentrySpan() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SentrySpanContext get context =>
      (super.noSuchMethod(Invocation.getter(#context),
          returnValue: _FakeSentrySpanContext_1()) as _i2.SentrySpanContext);
  @override
  DateTime get startTimestamp =>
      (super.noSuchMethod(Invocation.getter(#startTimestamp),
          returnValue: _FakeDateTime_2()) as DateTime);
  @override
  bool get finished =>
      (super.noSuchMethod(Invocation.getter(#finished), returnValue: false)
          as bool);
  @override
  set throwable(dynamic throwable) =>
      super.noSuchMethod(Invocation.setter(#throwable, throwable),
          returnValueForMissingStub: null);
  @override
  set status(_i2.SpanStatus? status) =>
      super.noSuchMethod(Invocation.setter(#status, status),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> finish({_i2.SpanStatus? status, DateTime? endTimestamp}) =>
      (super.noSuchMethod(
          Invocation.method(
              #finish, [], {#status: status, #endTimestamp: endTimestamp}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void removeData(String? key) =>
      super.noSuchMethod(Invocation.method(#removeData, [key]),
          returnValueForMissingStub: null);
  @override
  void removeTag(String? key) =>
      super.noSuchMethod(Invocation.method(#removeTag, [key]),
          returnValueForMissingStub: null);
  @override
  void setData(String? key, dynamic value) =>
      super.noSuchMethod(Invocation.method(#setData, [key, value]),
          returnValueForMissingStub: null);
  @override
  void setTag(String? key, String? value) =>
      super.noSuchMethod(Invocation.method(#setTag, [key, value]),
          returnValueForMissingStub: null);
  @override
  _i2.ISentrySpan startChild(String? operation,
          {String? description, DateTime? startTimestamp}) =>
      (super.noSuchMethod(
          Invocation.method(#startChild, [operation],
              {#description: description, #startTimestamp: startTimestamp}),
          returnValue: _FakeISentrySpan_3()) as _i2.ISentrySpan);
  @override
  _i2.SentryTraceHeader toSentryTrace() =>
      (super.noSuchMethod(Invocation.method(#toSentryTrace, []),
          returnValue: _FakeSentryTraceHeader_4()) as _i2.SentryTraceHeader);
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i7.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  _i3.MethodCodec get codec => (super.noSuchMethod(Invocation.getter(#codec),
      returnValue: _FakeMethodCodec_5()) as _i3.MethodCodec);
  @override
  _i4.BinaryMessenger get binaryMessenger =>
      (super.noSuchMethod(Invocation.getter(#binaryMessenger),
          returnValue: _FakeBinaryMessenger_6()) as _i4.BinaryMessenger);
  @override
  _i6.Future<T?> invokeMethod<T>(String? method, [dynamic arguments]) =>
      (super.noSuchMethod(Invocation.method(#invokeMethod, [method, arguments]),
          returnValue: Future<T?>.value()) as _i6.Future<T?>);
  @override
  _i6.Future<List<T>?> invokeListMethod<T>(String? method,
          [dynamic arguments]) =>
      (super.noSuchMethod(
          Invocation.method(#invokeListMethod, [method, arguments]),
          returnValue: Future<List<T>?>.value()) as _i6.Future<List<T>?>);
  @override
  _i6.Future<Map<K, V>?> invokeMapMethod<K, V>(String? method,
          [dynamic arguments]) =>
      (super.noSuchMethod(
          Invocation.method(#invokeMapMethod, [method, arguments]),
          returnValue: Future<Map<K, V>?>.value()) as _i6.Future<Map<K, V>?>);
  @override
  void setMethodCallHandler(
          _i6.Future<dynamic> Function(_i3.MethodCall)? handler) =>
      super.noSuchMethod(Invocation.method(#setMethodCallHandler, [handler]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SentryNative].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentryNative extends _i1.Mock implements _i8.SentryNative {
  MockSentryNative() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set appStartEnd(DateTime? _appStartEnd) =>
      super.noSuchMethod(Invocation.setter(#appStartEnd, _appStartEnd),
          returnValueForMissingStub: null);
  @override
  bool get didFetchAppStart =>
      (super.noSuchMethod(Invocation.getter(#didFetchAppStart),
          returnValue: false) as bool);
  @override
  void setNativeChannel(_i9.SentryNativeChannel? nativeChannel) =>
      super.noSuchMethod(Invocation.method(#setNativeChannel, [nativeChannel]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i9.NativeAppStart?> fetchNativeAppStart() =>
      (super.noSuchMethod(Invocation.method(#fetchNativeAppStart, []),
              returnValue: Future<_i9.NativeAppStart?>.value())
          as _i6.Future<_i9.NativeAppStart?>);
  @override
  _i6.Future<void> beginNativeFramesCollection() =>
      (super.noSuchMethod(Invocation.method(#beginNativeFramesCollection, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<_i9.NativeFrames?> endNativeFramesCollection(
          _i2.SentryId? traceId) =>
      (super.noSuchMethod(
              Invocation.method(#endNativeFramesCollection, [traceId]),
              returnValue: Future<_i9.NativeFrames?>.value())
          as _i6.Future<_i9.NativeFrames?>);
  @override
  void reset() => super.noSuchMethod(Invocation.method(#reset, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [ClientReportRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientReportRecorder extends _i1.Mock
    implements _i2.ClientReportRecorder {
  MockClientReportRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void recordLostEvent(
          _i10.DiscardReason? reason, _i11.DataCategory? category) =>
      super.noSuchMethod(
          Invocation.method(#recordLostEvent, [reason, category]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SentryEnvelope].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentryEnvelope extends _i1.Mock implements _i2.SentryEnvelope {
  MockSentryEnvelope() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SentryEnvelopeHeader get header => (super.noSuchMethod(
      Invocation.getter(#header),
      returnValue: _FakeSentryEnvelopeHeader_7()) as _i5.SentryEnvelopeHeader);
  @override
  List<_i2.SentryEnvelopeItem> get items => (super.noSuchMethod(
      Invocation.getter(#items),
      returnValue: <_i2.SentryEnvelopeItem>[]) as List<_i2.SentryEnvelopeItem>);
  @override
  _i6.Stream<List<int>> envelopeStream(_i2.SentryOptions? options) =>
      (super.noSuchMethod(Invocation.method(#envelopeStream, [options]),
          returnValue: Stream<List<int>>.empty()) as _i6.Stream<List<int>>);
  @override
  void addClientReport(_i2.ClientReport? clientReport) =>
      super.noSuchMethod(Invocation.method(#addClientReport, [clientReport]),
          returnValueForMissingStub: null);
}

/// A class which mocks [Hub].
///
/// See the documentation for Mockito's code generation for more information.
class MockHub extends _i1.Mock implements _i2.Hub {
  MockHub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SentryOptions get options =>
      (super.noSuchMethod(Invocation.getter(#options),
          returnValue: _FakeSentryOptions_8()) as _i2.SentryOptions);
  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);
  @override
  _i2.SentryId get lastEventId =>
      (super.noSuchMethod(Invocation.getter(#lastEventId),
          returnValue: _FakeSentryId_9()) as _i2.SentryId);
  @override
  _i6.Future<_i2.SentryId> captureEvent(_i2.SentryEvent? event,
          {dynamic stackTrace, dynamic hint, _i2.ScopeCallback? withScope}) =>
      (super.noSuchMethod(
              Invocation.method(#captureEvent, [
                event
              ], {
                #stackTrace: stackTrace,
                #hint: hint,
                #withScope: withScope
              }),
              returnValue: Future<_i2.SentryId>.value(_FakeSentryId_9()))
          as _i6.Future<_i2.SentryId>);
  @override
  _i6.Future<_i2.SentryId> captureException(dynamic throwable,
          {dynamic stackTrace, dynamic hint, _i2.ScopeCallback? withScope}) =>
      (super.noSuchMethod(
              Invocation.method(#captureException, [
                throwable
              ], {
                #stackTrace: stackTrace,
                #hint: hint,
                #withScope: withScope
              }),
              returnValue: Future<_i2.SentryId>.value(_FakeSentryId_9()))
          as _i6.Future<_i2.SentryId>);
  @override
  _i6.Future<_i2.SentryId> captureMessage(String? message,
          {_i2.SentryLevel? level,
          String? template,
          List<dynamic>? params,
          dynamic hint,
          _i2.ScopeCallback? withScope}) =>
      (super.noSuchMethod(
              Invocation.method(#captureMessage, [
                message
              ], {
                #level: level,
                #template: template,
                #params: params,
                #hint: hint,
                #withScope: withScope
              }),
              returnValue: Future<_i2.SentryId>.value(_FakeSentryId_9()))
          as _i6.Future<_i2.SentryId>);
  @override
  _i6.Future<void> captureUserFeedback(_i2.SentryUserFeedback? userFeedback) =>
      (super.noSuchMethod(
          Invocation.method(#captureUserFeedback, [userFeedback]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void addBreadcrumb(_i2.Breadcrumb? crumb, {dynamic hint}) => super
      .noSuchMethod(Invocation.method(#addBreadcrumb, [crumb], {#hint: hint}),
          returnValueForMissingStub: null);
  @override
  void bindClient(_i2.SentryClient? client) =>
      super.noSuchMethod(Invocation.method(#bindClient, [client]),
          returnValueForMissingStub: null);
  @override
  _i2.Hub clone() => (super.noSuchMethod(Invocation.method(#clone, []),
      returnValue: _FakeHub_10()) as _i2.Hub);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void configureScope(_i2.ScopeCallback? callback) =>
      super.noSuchMethod(Invocation.method(#configureScope, [callback]),
          returnValueForMissingStub: null);
  @override
  _i2.ISentrySpan startTransaction(String? name, String? operation,
          {String? description,
          DateTime? startTimestamp,
          bool? bindToScope,
          bool? waitForChildren,
          Duration? autoFinishAfter,
          bool? trimEnd,
          _i2.OnTransactionFinish? onFinish,
          Map<String, dynamic>? customSamplingContext}) =>
      (super.noSuchMethod(
              Invocation.method(#startTransaction, [
                name,
                operation
              ], {
                #description: description,
                #startTimestamp: startTimestamp,
                #bindToScope: bindToScope,
                #waitForChildren: waitForChildren,
                #autoFinishAfter: autoFinishAfter,
                #trimEnd: trimEnd,
                #onFinish: onFinish,
                #customSamplingContext: customSamplingContext
              }),
              returnValue: _i12.startTransactionShim(name, operation,
                  description: description,
                  startTimestamp: startTimestamp,
                  bindToScope: bindToScope,
                  waitForChildren: waitForChildren,
                  autoFinishAfter: autoFinishAfter,
                  trimEnd: trimEnd,
                  onFinish: onFinish,
                  customSamplingContext: customSamplingContext))
          as _i2.ISentrySpan);
  @override
  _i2.ISentrySpan startTransactionWithContext(
          _i2.SentryTransactionContext? transactionContext,
          {Map<String, dynamic>? customSamplingContext,
          DateTime? startTimestamp,
          bool? bindToScope,
          bool? waitForChildren,
          Duration? autoFinishAfter,
          bool? trimEnd,
          _i2.OnTransactionFinish? onFinish}) =>
      (super.noSuchMethod(
          Invocation.method(#startTransactionWithContext, [
            transactionContext
          ], {
            #customSamplingContext: customSamplingContext,
            #startTimestamp: startTimestamp,
            #bindToScope: bindToScope,
            #waitForChildren: waitForChildren,
            #autoFinishAfter: autoFinishAfter,
            #trimEnd: trimEnd,
            #onFinish: onFinish
          }),
          returnValue: _FakeISentrySpan_3()) as _i2.ISentrySpan);
  @override
  _i6.Future<_i2.SentryId> captureTransaction(
          _i2.SentryTransaction? transaction) =>
      (super.noSuchMethod(Invocation.method(#captureTransaction, [transaction]),
              returnValue: Future<_i2.SentryId>.value(_FakeSentryId_9()))
          as _i6.Future<_i2.SentryId>);
  @override
  void setSpanContext(
          dynamic throwable, _i2.ISentrySpan? span, String? transaction) =>
      super.noSuchMethod(
          Invocation.method(#setSpanContext, [throwable, span, transaction]),
          returnValueForMissingStub: null);
}
