# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  - "packages/flutter/lib/src/span_frame_metrics_collector.dart"
  - "packages/flutter/lib/src/integrations/native_app_start_integration.dart"
  - "packages/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt"
  - "packages/flutter/ios/Classes/SentryFlutterPluginApple.swift"
  - "packages/flutter/lib/src/screenshot/recorder.dart"
  - "packages/flutter/lib/src/screenshot/widget_filter.dart"
  - "packages/flutter/lib/src/native/java/android_replay_recorder.dart"
