# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  - "packages/sentry_flutter/lib/src/frames_tracking/span_frame_metrics_collector.dart"
  - "packages/sentry_flutter/lib/src/app_start/**"
  - "packages/sentry_flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt"
  - "packages/sentry_flutter/darwin/sentry_flutter/Sources/sentry_flutter/SentryFlutterPlugin.swift"
  - "packages/sentry_flutter/lib/src/screen_capture/recorder.dart"
  - "packages/sentry_flutter/lib/src/screen_capture/widget_filter.dart"
  - "packages/sentry_flutter/lib/src/native/java/android_replay_recorder.dart"
