changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - renovate

  categories:
    - title: Breaking Changes
      commit_patterns:
        - "^(?<type>\\w+(?:\\((?<scope>[^)]+)\\))?!:\\s*)"
      semver: major
    - title: Features
      commit_patterns:
        - "^(?<type>feat(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
      semver: minor
    - title: Fixes
      commit_patterns:
        - "^(?<type>fix(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
        - '^Revert "'
      semver: patch
    - title: Enhancements
      commit_patterns:
        - "^(?<type>(?:perf|impr|enh)(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
      semver: patch
    - title: Internal Changes
      commit_patterns:
        - "^(?<type>(?:build|refactor|meta|chore|ci|ref|perf|tests?|style|docs)(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
