minVersion: 0.29.0
changelogPolicy: auto
artifactProvider:
  name: none
targets:
  - name: pub-dev
    packages:
      dart:
      flutter:
      logging:
      dio:
  - name: github
  - name: registry
    sdks:
      pub:sentry:
      pub:sentry_flutter:
