minVersion: 0.29.2
changelogPolicy: auto
artifactProvider:
  name: none
targets:
  - name: pub-dev
    packages:
      dart:
      flutter:
      logging:
      dio:
      file:
      sqflite:
      hive:
      drift:
  - name: github
  - name: registry
    sdks:
      pub:sentry:
      pub:sentry_flutter:
      pub:sentry_logging:
      pub:sentry_dio:
      pub:sentry_file:
      pub:sentry_sqflite:
      pub:sentry_drift:
      pub:sentry_hive:
      # Initial release on pub.dev needed first before uncommenting
      # pub:sentry_isar:
