name: sentry_dart_workspace
packages:
  - 'packages/*'
  - 'packages/*/*'
  - 'packages/*/*/*'

ignore:
  - 'packages/dart/example_web/build'

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: git config core.hooksPath .githooks

ide:
  intellij:
    moduleNamePrefix: ''

scripts:
  analyze:dart:
    run: melos exec --fail-fast -- dart analyze --fatal-warnings
    description: Run dart analyze on all Dart-only packages.
    packageFilters:
      flutter: false
      dirExists: lib

  analyze:flutter:
    run: melos exec --fail-fast -- flutter analyze --fatal-warnings
    description: Run flutter analyze on all Flutter packages.
    packageFilters:
      flutter: true
      dirExists: lib

  format:
    run: melos exec -- dart format .
    description: Apply formatting to all packages.
    packageFilters:
      dirExists: lib

  test:dart:
    run: melos exec --fail-fast -- dart test
    description: Run tests for Dart-only packages.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec --fail-fast -- flutter test
    description: Run tests for Flutter packages.
    packageFilters:
      flutter: true
      dirExists: test

  # Lifecycle script, executed as part of `melos clean`.
  postclean: melos exec -- "flutter clean"

