name: sentry_link
description: Automatic capture of exceptions and GraphQL errors for the gql eco-system, like graphql and ferry
version: 0.5.2
repository: https://github.com/ueman/dart-packages/
issue_tracker: https://github.com/ueman/dart-packages/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  gql_error_link: ">=0.2.0 <2.0.0"
  gql_exec: ">=0.4.4 <2.0.0"
  gql_link: ">=0.5.0 <2.0.0"
  gql: ">=0.14.0 <2.0.0"
  sentry: ^8.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  graphql: ^5.1.3
