name: sentry_grpc_example_grpc4
description: sentry_grpc example using grpc 4.x
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: '>=4.0.4 <5.0.0'
  http: ^1.2.0
  sentry: 9.20.0
  sentry_grpc:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
