name: integration_test_app
description: An application to run integration & end to end tests of sentry packages.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sentry:
  sentry_flutter:
  http: ^0.13.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

sentry:
  upload_source_maps: true
  upload_sources: true
  project: sentry-flutter
  org: sentry-sdks
  wait_for_processing: true
  commits: true
  ignore_missing: true