#!/usr/bin/env bash
set -euo pipefail

# This script bumps the Sentry JavaScript SDK used by the Flutter web integration.
# The expected interface is identical to the other updater scripts used by the
# monorepo so that it can be consumed by the generic getsentry/updater workflow.
#
# Usage: ./update-js.sh <command>
#   get-version   – prints the currently used SDK version (read from sentry-js-sdk.yaml)
#   get-repo      – prints the upstream Git repository URL
#   set-version X – updates the version to X, refreshes integrity hashes and
#                   regenerates the Dart constant file used by the web runtime

VERSION_DART_FILE="$(git rev-parse --show-toplevel)/packages/flutter/lib/src/web/sentry_js_sdk_version.dart"

get_current_version() {
  awk -F"'" '/sentryJsSdkVersion/ { print $2 }' "$VERSION_DART_FILE"
}

# Regenerates the Dart helper that exposes the SDK version as a compile-time
# constant so that the rest of the code can simply import it.
write_version_dart() {
  local version="$1"
  local integrity_prod="$2"
  local integrity_dbg="$3"
  local integrity_replay_prod="$4"
  local integrity_replay_dbg="$5"
  local integrity_replay_canvas_prod="$6"
  local integrity_replay_canvas_dbg="$7"
  cat >"$VERSION_DART_FILE" <<EOF
import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '$version';

@internal
const productionIntegrity =
    'sha384-$integrity_prod';

@internal
const debugIntegrity =
    'sha384-$integrity_dbg';

@internal
const productionReplayIntegrity =
    'sha384-$integrity_replay_prod';

@internal
const debugReplayIntegrity =
    'sha384-$integrity_replay_dbg';

@internal
const productionReplayCanvasIntegrity =
    'sha384-$integrity_replay_canvas_prod';

@internal
const debugReplayCanvasIntegrity =
    'sha384-$integrity_replay_canvas_dbg';
EOF
}

compute_integrity() {
  local url="$1"
  curl -fsSL "$url" | openssl dgst -sha384 -binary | openssl base64 -A
}

case "${1:-}" in
  get-version)
    get_current_version
    ;;

  get-repo)
    echo "https://github.com/getsentry/sentry-javascript.git"
    ;;

  set-version)
    new_version="$2"

    # Fetch SRI hashes for the given version.
    min_js_url="https://browser.sentry-cdn.com/$new_version/bundle.tracing.min.js"
    dbg_js_url="https://browser.sentry-cdn.com/$new_version/bundle.tracing.js"
    min_replay_js_url="https://browser.sentry-cdn.com/$new_version/bundle.tracing.replay.min.js"
    dbg_replay_js_url="https://browser.sentry-cdn.com/$new_version/bundle.tracing.replay.js"
    min_replay_canvas_js_url="https://browser.sentry-cdn.com/$new_version/replay-canvas.min.js"
    dbg_replay_canvas_js_url="https://browser.sentry-cdn.com/$new_version/replay-canvas.js"

    # Compute the SHA-384 SRI hashes (without the sha384- prefix)
    integrity_prod=$(compute_integrity "$min_js_url")
    integrity_dbg=$(compute_integrity "$dbg_js_url")
    integrity_replay_prod=$(compute_integrity "$min_replay_js_url")
    integrity_replay_dbg=$(compute_integrity "$dbg_replay_js_url")
    integrity_replay_canvas_prod=$(compute_integrity "$min_replay_canvas_js_url")
    integrity_replay_canvas_dbg=$(compute_integrity "$dbg_replay_canvas_js_url")

    # Persist changes
    write_version_dart "$new_version" "$integrity_prod" "$integrity_dbg" "$integrity_replay_prod" "$integrity_replay_dbg" "$integrity_replay_canvas_prod" "$integrity_replay_canvas_dbg"
    ;;

  *)
    echo "Unknown argument $1" >&2
    exit 1
    ;;
esac
