name: sentry_grpc_example_grpc5
description: sentry_grpc example using grpc 5.x
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  grpc: '>=5.0.0 <6.0.0'
  sentry: 9.20.0
  sentry_grpc:
    path: ../..

dev_dependencies:
  lints: ^5.0.0
