name: microbenchmarks
description: Small benchmarks for very specific parts of the Flutter framework.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.15.0
  test: ^1.25.14
  benchmarking: ^0.6.1
  sentry_flutter:
    path: ../

flutter:
  uses-material-design: true
