include: package:lints/recommended.yaml

linter: 
  rules:
   - prefer_single_quotes
   - depend_on_referenced_packages
   - always_use_package_imports

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # ignore sentry/path on pubspec as we change it on deployment
    invalid_dependency: ignore