import 'dart:async';

import 'package:meta/meta.dart';

import '../../../sentry.dart';
import '../span/sentry_span_v2.dart';
import 'attributes_aggregator.dart';

/// Pipeline for systematic telemetry attribute enrichment.
///
/// This enricher manages **global, systematic attribute providers** that apply
/// to all telemetry items. It is NOT the source of truth for ALL enrichment
/// in the SDK.
///
/// Attributes are merged in the following order (highest to lowest priority):
/// 1. **Item attributes** - Attributes already set on the telemetry item
/// 2. **Scope attributes** - Attributes from the current scope
/// 3. **Provider attributes** - Attributes generated by registered providers
@internal
final class GlobalTelemetryEnricher {
  final Hub _hub;
  final _providers = <TelemetryAttributesProvider>[];

  late final _aggregator = TelemetryAttributesAggregator(_providers);

  GlobalTelemetryEnricher({Hub? hub}) : _hub = hub ?? HubAdapter();

  TelemetryAttributesProviderContext get _context =>
      TelemetryAttributesProviderContext(
          options: _hub.options, scope: _hub.scope);

  FutureOr<void> enrichLog(SentryLog log) => _enrichAttributes(
        targetAttributes: log.attributes,
        telemetry: log,
        applyAttributes: (attributes) {
          log.attributes = attributes;
        },
      );

  FutureOr<void> enrichSpan(RecordingSentrySpanV2 span) => _enrichAttributes(
        targetAttributes: span.attributes,
        telemetry: span,
        applyAttributes: (attributes) {
          span.setAttributes(attributes);
        },
      );

  FutureOr<void> _enrichAttributes({
    required Map<String, SentryAttribute> targetAttributes,
    required Object telemetry,
    required void Function(Map<String, SentryAttribute>) applyAttributes,
  }) {
    // Scope is also set by the SDK user so it should be merged first.
    final mergedAttributes = targetAttributes
      ..addAllIfAbsent(_hub.scope.attributes);

    final aggregatedAttributes = _aggregator.build(telemetry, _context);
    if (aggregatedAttributes is Map<String, SentryAttribute>) {
      mergedAttributes.addAllIfAbsent(aggregatedAttributes);
      applyAttributes(mergedAttributes);
      return null;
    }

    return aggregatedAttributes.then((providerAttributes) {
      mergedAttributes.addAllIfAbsent(providerAttributes);
      applyAttributes(mergedAttributes);
    });
  }

  /// Registers a new attribute provider and processed in registration order.
  ///
  /// Duplicate registrations are ignored.
  void registerAttributesProvider(TelemetryAttributesProvider provider) {
    if (_providers.contains(provider)) {
      return;
    }
    _providers.add(provider);
  }
}

extension _AddAllAbsentX<K, V> on Map<K, V> {
  void addAllIfAbsent(Map<K, V> other) {
    for (final e in other.entries) {
      putIfAbsent(e.key, () => e.value);
    }
  }
}
