import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '9.43.0';

@internal
const productionIntegrity =
    'sha384-SLEQt2FiMR3rcTCgyDpcl1n+XNt4FL8sOTjBLO8txFvn8hJ7SoZNGf8tvMlSMpcP';

@internal
const debugIntegrity =
    'sha384-Zpy/V2cK65X7Hp5xgU1TK4nJPlU6wp6Dr/qmUHFfAJzcpxoro8rxFUrqgU7yfyz4';
