import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '9.41.0';

@internal
const productionIntegrity =
    'sha384-r/YoQxyD2g4gSbNPInkBufUjDkbcvzkQMO6aBnZ7tJexAZVslAsNI+7f8Jik4OC7';

@internal
const debugIntegrity =
    'sha384-BiJJLnm1qBnWECRFVSfMSO0gwhXR9AIhFk5ZZBGSE6aDJ46TCac0Ew7jD4m44HHA';
