name: sentry_firebase_remote_config
description: "Sentry integration to use feature flags from Firebase Remote Config."
version: 9.0.0-alpha.2
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^5.4.3
  sentry: ^9.0.0-alpha.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  coverage: ^1.3.0
  mockito: ^5.1.0
  build_runner: ^2.4.6
