name: Upload test results
description: Upload JUnit test results to Codecov
inputs:
  token:
    description: Codecov token
    required: true
  flags:
    description: Codecov flag name (e.g. sentry_dio-Linux-stable)
    required: true

runs:
  using: composite

  steps:
    - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # pin@v5.5.2
      with:
        token: ${{ inputs.token }}
        flags: ${{ inputs.flags }}
        report_type: test_results
        fail_ci_if_error: false
        verbose: true
