name: publish_validation
description: Command-line application for validating publish dry runs.
publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
