include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/** # the example has its own 'analysis_options.yaml'
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: error
    # treat missing returns as a warning (not a hint)
    missing_return: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_relative_imports: true
    unnecessary_brace_in_string_interps: true
    prefer_function_declarations_over_variables: false
    no_leading_underscores_for_local_identifiers: false
    avoid_renaming_method_parameters: false
    unawaited_futures: true
