include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use_from_same_package: warning
    invalid_dependency: ignore
    unnecessary_import: ignore
  exclude:
    - example/**

linter:
  rules:
    - prefer_final_locals
    - public_member_api_docs
    - prefer_single_quotes
    - prefer_relative_imports
    - unnecessary_brace_in_string_interps
    - implementation_imports
    - require_trailing_commas
    - unawaited_futures
