name: Flutter tests
description: Run Flutter tests
inputs:
  directory:
    description: The directory to run tests in
    required: false
    default: ''

runs:
  using: composite

  steps:
    - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # pin@v2.18.0
      with:
        channel: ${{ matrix.sdk }}

    - uses: actions/setup-java@v4
      if: ${{ matrix.target == 'android' }}
      with:
        java-version: '17'
        distribution: 'adopt'

    # Install required dependencies for Flutter on Linux on Ubuntu
    - name: "Setup Linux"
      if: matrix.target == 'linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake dbus libblkid-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb libcurl4-openssl-dev network-manager upower

    - run: flutter pub get
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Test VM
      if: matrix.target != 'js' && matrix.target != 'wasm'
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        if ${{ (matrix.target == 'linux' && matrix.sdk == 'stable' && 'true') || 'false' }} ; then
          flutter test --coverage --test-randomize-ordering-seed=random
          dart run remove_from_coverage -f coverage/lcov.info -r 'binding.dart'
        else
          flutter test --test-randomize-ordering-seed=random
        fi

    - name: Test web (${{ matrix.target }})
      if: matrix.target == 'js' || matrix.target == 'wasm'
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        flutter test --platform chrome ${{ (matrix.target == 'wasm' && '--wasm') || '' }} --test-randomize-ordering-seed=random --exclude-tags canvasKit
        flutter test --platform chrome ${{ (matrix.target == 'wasm' && '--wasm') || '' }} --test-randomize-ordering-seed=random --tags canvasKit
