import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.14.0';

@internal
const productionIntegrity =
    'sha384-GkU7zTgqS2CTo0QmxEiOsIQJq68+tkFqUhuqkW+4j43VSUgFywx4aaucNqxBE0AD';

@internal
const debugIntegrity =
    'sha384-ScN7GvJPxcPfDnrcAUhK6bFeool2TZejL9Qkj9ISl7V3X2VAH5OtWwiGRYa65MFv';
