import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.12.0';

@internal
const productionIntegrity =
    'sha384-hZz/ml2YZIhOWVkQMb+pYrqx6Upit9QtIAJsZN3721R22p/YGdbMB9L9e7FQ8sL1';

@internal
const debugIntegrity =
    'sha384-yAjQ66keLlOYnV2NyCNn9zmbHxX4AQnduN1wTAYT4uEA6Qy2aYI1+0ZVbuDbS6O+';
