import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '11.0.0';

@internal
const productionIntegrity =
    'sha384-TcpSGbL8WtdpR8lXDGGaurUtinn44aaUcN/5iratedpnLQZYJpnJlzK4pdS8sBn5';

@internal
const debugIntegrity =
    'sha384-hlI/tESUJSweV0xHfXj9uDHTAXNGExvDMzSQy/tiwSZ/o14fLbBfq7wKSCebkOgN';
