default_platform(:ios)

platform :ios do

  desc "Bump Build Number"
  lane :bump_build_number do
    increment_build_number(
      build_number: ENV["FASTLANE_BUILD_NUMBER"],
      xcodeproj: "./Runner.xcodeproj"
    )
  end

  desc "Build Release"
  lane :build_release do

    setup_ci

    sync_code_signing(
      type: "appstore",
      readonly: true,
      app_identifier: ["io.sentry.flutter.sample"]
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      include_symbols: true,
      export_method: "app-store",
      archive_path: "sentry-flutter-example"
    )

    delete_keychain(
      name: "fastlane_tmp_keychain"
    ) unless is_ci
  end

  desc "Upload to TestFlight"
  lane :upload_testflight do

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"]
    )

    testflight(
      skip_waiting_for_build_processing: true,
    )

    sentry_upload_dif(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'sentry-sdks',
      project_slug: 'sentry-cocoa',
      include_sources: true
    )
  end

end
