name: Dart tests
description: Run Dart tests
inputs:
  directory:
    description: The directory to run tests in
    required: false
    default: ''

runs:
  using: composite

  steps:
    - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # pin@v1
      with:
        sdk: ${{ matrix.sdk }}

    - run: dart pub get
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Test VM
      run: dart test -p vm --coverage=coverage --test-randomize-ordering-seed=random --chain-stack-traces
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Test dart2js
      run: dart test -p chrome --test-randomize-ordering-seed=random --chain-stack-traces
      shell: bash
      working-directory: ${{ inputs.directory }}
