name: Clear SwiftPM cache
description: Remove stale SwiftPM package and binary artifact caches

runs:
  using: composite
  steps:
    - name: Clear SwiftPM cache
      shell: bash
      run: bash ./.github/actions/clear-swiftpm-cache/clear-swiftpm-cache.sh
