name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  danger:
    uses: getsentry/github-workflows/.github/workflows/danger.yml@v2
