name: sentry-link
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths:
      - '!**/*.md'
      - '!**/class-diagram.svg'
      - '.github/workflows/link.yml'
      - '.github/workflows/analyze.yml'
      - '.github/actions/dart-test/**'
      - '.github/actions/coverage/**'
      - 'packages/dart/**'
      - 'packages/link/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: '${{ matrix.os }} | ${{ matrix.sdk }}'
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
        sdk: [stable, beta]

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/dart-test
        with:
          directory: packages/link
          web: false

  #       TODO: don't set coverage for now to finish publishing it
  #      - uses: ./.github/actions/coverage
  #        if: runner.os == 'Linux' && matrix.sdk == 'stable'
  #        with:
  #          token: ${{ secrets.CODECOV_TOKEN }}
  #          directory: link
  #          coverage: sentry_link
  #          min-coverage: 55

  analyze:
    uses: ./.github/workflows/analyze.yml
    with:
      package: packages/link
