name: sentry-supabase
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths:
      - '!**/*.md'
      - '!**/class-diagram.svg'
      - '.github/workflows/supabase.yml'
      - '.github/workflows/analyze.yml'
      - '.github/actions/dart-test/**'
      - '.github/actions/coverage/**'
      - '.github/actions/test-results/**'
      - 'packages/dart/**'
      - 'packages/flutter/**'
      - 'packages/supabase/**'

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: '${{ matrix.target }} | ${{ matrix.sdk }}'
    runs-on: ${{ matrix.target == 'linux' && 'ubuntu' || matrix.target }}-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target: [macos, linux, windows]
        sdk: [stable, beta]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/flutter-test
        with:
          directory: packages/supabase

      - uses: ./.github/actions/coverage
        if: matrix.target == 'linux' && matrix.sdk == 'stable'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/supabase
          coverage: sentry_supabase
          min-coverage: 85

      - uses: ./.github/actions/test-results
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: sentry_supabase-${{ matrix.target }}-${{ matrix.sdk }}

  analyze:
    uses: ./.github/workflows/analyze.yml
    with:
      package: packages/supabase
      sdk: flutter
