name: Update JS SDK

on:
  # Daily at 05:00 UTC
  schedule:
    - cron: '0 5 * * *'
  # Allow manual trigger
  workflow_dispatch:
  pull_request:

jobs:
  bump-js-sdk:
    uses: getsentry/github-workflows/.github/workflows/updater.yml@v2
    with:
      path: flutter/scripts/update-js.sh
      name: JavaScript SDK
    secrets:
      api-token: ${{ secrets.CI_DEPLOY_KEY }}