name: Update JS SDK

on:
  # Daily at 05:00 UTC
  schedule:
    - cron: '0 5 * * *'
  # Allow manual trigger
  workflow_dispatch:
  # Triggered by external hooks whenever a new tag of the JS SDK is published.
  repository_dispatch:
    types: [sentry-js-sdk-release]

jobs:
  bump-js-sdk:
    uses: getsentry/github-workflows/.github/workflows/updater.yml@v2
    with:
      path: flutter/scripts/update-js.sh
      name: JavaScript SDK
    secrets:
      api-token: ${{ secrets.CI_DEPLOY_KEY }}