name: Update Dependencies

on:
  # Run every day.
  schedule:
    - cron: '0 3 * * *'
  # And on every PR merge so we get the updated dependencies ASAP, and to make sure the changelog doesn't conflict.
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          path: packages/flutter/scripts/update-android.sh
          name: Android SDK
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  cocoa:
    runs-on: macos-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          path: packages/flutter/scripts/update-cocoa.sh
          name: Cocoa SDK
          pattern: '^8\.' # Only update Cocoa SDK 8.x.x until the next Sentry Flutter major v10
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          path: packages/flutter/scripts/update-js.sh
          name: JavaScript SDK
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  native:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          path: packages/flutter/scripts/update-native.sh
          name: Native SDK
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  metrics-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        id: updater
        with:
          path: metrics/flutter.properties
          name: Flutter SDK Metrics
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}
      - if: steps.updater.outputs.prUrl
        run: gh pr edit "${{ steps.updater.outputs.prUrl }}" --add-label "skip-changelog"
        env:
          GH_TOKEN: ${{ github.token }}

  symbol-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        id: updater
        with:
          path: scripts/update-symbol-collector.sh
          name: Symbol Collector CLI
          changelog-entry: false
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}
      - if: steps.updater.outputs.prUrl
        run: gh pr edit "${{ steps.updater.outputs.prUrl }}" --add-label "skip-changelog"
        env:
          GH_TOKEN: ${{ github.token }}
